# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/simple_calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Simple_calculator(object):
    def setupUi(self, Simple_calculator):
        Simple_calculator.setObjectName("Simple_calculator")
        Simple_calculator.resize(338, 242)
        self.gridLayout_3 = QtWidgets.QGridLayout(Simple_calculator)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Simple_calculator)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(317, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_11 = QtWidgets.QPushButton(Simple_calculator)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_2.addWidget(self.pushButton_11, 3, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(Simple_calculator)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 2, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(Simple_calculator)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(Simple_calculator)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(Simple_calculator)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(Simple_calculator)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 2, 0, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(Simple_calculator)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_2.addWidget(self.pushButton_16, 3, 3, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(Simple_calculator)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_2.addWidget(self.pushButton_13, 0, 3, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(Simple_calculator)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_2.addWidget(self.pushButton_14, 1, 3, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(Simple_calculator)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_2.addWidget(self.pushButton_12, 3, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(Simple_calculator)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_2.addWidget(self.pushButton_10, 0, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(Simple_calculator)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Simple_calculator)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(Simple_calculator)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_2.addWidget(self.pushButton_9, 2, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Simple_calculator)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 3, 2, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(Simple_calculator)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_2.addWidget(self.pushButton_15, 2, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)

        self.retranslateUi(Simple_calculator)
        QtCore.QMetaObject.connectSlotsByName(Simple_calculator)

    def retranslateUi(self, Simple_calculator):
        _translate = QtCore.QCoreApplication.translate
        Simple_calculator.setWindowTitle(_translate("Simple_calculator", "Form"))
        self.label.setText(_translate("Simple_calculator", "0"))
        self.pushButton_11.setText(_translate("Simple_calculator", "0"))
        self.pushButton_5.setText(_translate("Simple_calculator", "8"))
        self.pushButton_3.setText(_translate("Simple_calculator", "3"))
        self.pushButton_7.setText(_translate("Simple_calculator", "5"))
        self.pushButton_6.setText(_translate("Simple_calculator", "6"))
        self.pushButton_8.setText(_translate("Simple_calculator", "7"))
        self.pushButton_16.setText(_translate("Simple_calculator", "/"))
        self.pushButton_13.setText(_translate("Simple_calculator", "+"))
        self.pushButton_14.setText(_translate("Simple_calculator", "-"))
        self.pushButton_12.setText(_translate("Simple_calculator", "C"))
        self.pushButton_10.setText(_translate("Simple_calculator", "2"))
        self.pushButton_4.setText(_translate("Simple_calculator", "1"))
        self.pushButton_2.setText(_translate("Simple_calculator", "4"))
        self.pushButton_9.setText(_translate("Simple_calculator", "9"))
        self.pushButton.setText(_translate("Simple_calculator", "="))
        self.pushButton_15.setText(_translate("Simple_calculator", "x"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Simple_calculator = QtWidgets.QWidget()
    ui = Ui_Simple_calculator()
    ui.setupUi(Simple_calculator)
    Simple_calculator.show()
    sys.exit(app.exec_())
